# Generated by Django 5.2.17 on 2026-08-22 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(blank=True, max_length=128)),
                ('bio', models.TextField(blank=True)),
                ('specialisations', models.JSONField(blank=True, default=list)),
                ('accepts_consultations', models.BooleanField(default=False)),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='Example: {"monday": [["09:00","17:00"]], "tuesday": [["09:00","17:00"]]}')),
                ('timezone_name', models.CharField(default='Africa/Johannesburg', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
