# Generated by Django 5.2.17 on 2026-08-23 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_public_booking_legal_activation'),
        ('content', '0002_seo'),
        ('services', '0002_seo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(default='Terms & Conditions', max_length=255)),
                ('body', models.TextField()),
                ('effective_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('summary', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='next_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_faqs', to='services.service'),
        ),
        migrations.AddField(
            model_name='faq',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(db_index=True, default='general', max_length=64),
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms_version', models.CharField(max_length=32)),
                ('privacy_version', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(default='consultation_booking', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_acceptances', to='consultations.appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
                ('terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='content.termsdocument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'terms_version'], name='content_leg_user_id_9669a2_idx')],
            },
        ),
    ]
