# Generated by Django 5.2.17 on 2026-08-22 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='ZAR', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('consultant', models.ForeignKey(blank=True, help_text='Leave empty to block for all consultants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'consultant')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='PENDING', max_length=24)),
                ('meeting_link', models.URLField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='applications.application')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultant_appointments', to=settings.AUTH_USER_MODEL)),
                ('consultation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='consultations.consultationtype')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['consultant', 'starts_at'], name='consultatio_consult_64a3ea_idx'), models.Index(fields=['client', 'starts_at'], name='consultatio_client__a3b5ff_idx')],
            },
        ),
    ]
