# Generated by Django 5.2.17 on 2026-08-23 01:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_external_tracking'),
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotHold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('converted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='calendar_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timezone_name',
            field=models.CharField(default='Africa/Johannesburg', max_length=64),
        ),
        migrations.AddField(
            model_name='consultationtype',
            name='cancellation_hours',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='consultationtype',
            name='color',
            field=models.CharField(default='#FF6B21', max_length=16),
        ),
        migrations.AddField(
            model_name='consultationtype',
            name='icon',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='consultationtype',
            name='reschedule_hours',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='PENDING', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'COMPLETED', 'NO_SHOW', 'RESCHEDULED'])), fields=('consultant', 'starts_at'), name='uniq_active_consultant_slot'),
        ),
        migrations.AddField(
            model_name='slothold',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slothold',
            name='consultation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_holds', to='consultations.consultationtype'),
        ),
        migrations.AddIndex(
            model_name='slothold',
            index=models.Index(fields=['consultant', 'starts_at', 'expires_at'], name='consultatio_consult_3efd0a_idx'),
        ),
    ]
