import { createApi } from "@reduxjs/toolkit/query/react";

import { asList, asPage } from "@/lib/api";
import { baseQueryWithReauth } from "@/store/baseQuery";
import type {
  ApplicationAssignRequest,
  ApplicationCreateRequest,
  ApplicationDashboard,
  ApplicationDetail,
  ApplicationList,
  ApplicationNote,
  ApplicationNoteCreateRequest,
  ApplicationQuery,
  ApplicationStatus,
  ApplicationTransitionRequest,
  Appointment,
  AppointmentCreateRequest,
  AppointmentSlot,
  ArticleDetail,
  ArticleList,
  AuditLog,
  ClientActivity,
  ClientProfile,
  ClientProfileUpdate,
  CmsPage,
  ConsultationType,
  Conversation,
  DashboardStats,
  DetailResponse,
  DocumentQuery,
  DocumentRequestCreate,
  DocumentRequestRecord,
  DocumentReviewRequest,
  DocumentSubmission,
  DocumentType,
  ExternalTrackingAdminRow,
  FAQ,
  HomeContent,
  PublicSeoIndex,
  SeoLandingDetail,
  SeoLandingList,
  Inquiry,
  InquiryCreateRequest,
  InquirySetStatusRequest,
  Invoice,
  InvoiceCreateRequest,
  InvoiceQuery,
  LoginRequest,
  LoginResponse,
  MarkAllReadResponse,
  MeUpdate,
  MeUser,
  Message,
  Notification,
  Paginated,
  PasswordChangeRequest,
  PublicConsultant,
  RecordPaymentRequest,
  RegisterRequest,
  RegisterResponse,
  SendMessageRequest,
  ServiceDetail,
  ServiceList,
  ApplicationTracking,
  ApplicationTrackingHistoryItem,
  ManualTrackingUpdate,
  SiteSetting,
  StaffClient,
  StaffUser,
  Testimonial,
  TrackingDetailsUpdate,
} from "@/types/api";

export const api = createApi({
  reducerPath: "api",
  baseQuery: baseQueryWithReauth,
  tagTypes: [
    "Auth",
    "Application",
    "Document",
    "Appointment",
    "Conversation",
    "Message",
    "Notification",
    "Invoice",
    "Service",
    "ClientProfile",
    "Content",
    "Inquiry",
    "Client",
    "Staff",
    "Report",
    "Audit",
    "DocumentType",
    "Tracking",
  ],
  endpoints: (builder) => ({
    register: builder.mutation<RegisterResponse, RegisterRequest>({
      query: (body) => ({ url: "/auth/register", method: "POST", body }),
    }),
    login: builder.mutation<LoginResponse, LoginRequest>({
      query: (body) => ({ url: "/auth/login", method: "POST", body }),
    }),
    getMe: builder.query<MeUser, void>({
      query: () => "/auth/me",
      providesTags: ["Auth"],
    }),
    updateMe: builder.mutation<MeUser, MeUpdate>({
      query: (body) => ({ url: "/auth/me", method: "PATCH", body }),
      invalidatesTags: ["Auth"],
    }),
    changePassword: builder.mutation<DetailResponse, PasswordChangeRequest>({
      query: (body) => ({ url: "/auth/password/change", method: "POST", body }),
    }),
    getHomeContent: builder.query<HomeContent, void>({
      query: () => "/content/settings/home",
      providesTags: ["Content"],
    }),
    getServices: builder.query<ServiceList[], void>({
      query: () => "/services",
      transformResponse: (response: unknown) => asList<ServiceList>(response),
      providesTags: ["Service"],
    }),
    getService: builder.query<ServiceDetail, string>({
      query: (slug) => `/services/${slug}`,
      providesTags: (_result, _error, slug) => [{ type: "Service", id: slug }],
    }),
    getPage: builder.query<CmsPage, string>({
      query: (slug) => `/content/pages/${slug}`,
      providesTags: ["Content"],
    }),
    getFaqs: builder.query<FAQ[], void>({
      query: () => "/content/faqs",
      transformResponse: (response: unknown) => asList<FAQ>(response),
      providesTags: ["Content"],
    }),
    getTestimonials: builder.query<Testimonial[], void>({
      query: () => "/content/testimonials",
      transformResponse: (response: unknown) => asList<Testimonial>(response),
      providesTags: ["Content"],
    }),
    getArticles: builder.query<Paginated<ArticleList>, { page?: number } | void>({
      query: (args) => ({ url: "/content/articles", params: args && args.page ? { page: args.page } : undefined }),
      transformResponse: (response: unknown) => asPage<ArticleList>(response),
      providesTags: ["Content"],
    }),
    getArticle: builder.query<ArticleDetail, string>({
      query: (slug) => `/content/articles/${slug}`,
      providesTags: ["Content"],
    }),
    getPublicSeo: builder.query<PublicSeoIndex, void>({
      query: () => "/content/settings/public-seo",
      providesTags: ["Content"],
    }),
    getLandings: builder.query<SeoLandingList[], { kind?: "country" | "location" } | void>({
      query: (args) => ({ url: "/content/landings", params: args ?? undefined }),
      transformResponse: (response: unknown) => asList<SeoLandingList>(response),
      providesTags: ["Content"],
    }),
    getLanding: builder.query<SeoLandingDetail, string>({
      query: (slug) => `/content/landings/${slug}`,
      providesTags: (_result, _error, slug) => [{ type: "Content", id: slug }],
    }),
    updateLanding: builder.mutation<SeoLandingDetail, { slug: string; body: Partial<SeoLandingDetail> }>({
      query: ({ slug, body }) => ({ url: `/content/landings/${slug}`, method: "PATCH", body }),
      invalidatesTags: ["Content"],
    }),
    updatePage: builder.mutation<CmsPage, { slug: string; body: Partial<CmsPage> }>({
      query: ({ slug, body }) => ({ url: `/content/pages/${slug}`, method: "PATCH", body }),
      invalidatesTags: ["Content"],
    }),
    updateArticle: builder.mutation<ArticleDetail, { slug: string; body: Partial<ArticleDetail> }>({
      query: ({ slug, body }) => ({ url: `/content/articles/${slug}`, method: "PATCH", body }),
      invalidatesTags: ["Content"],
    }),
    updateService: builder.mutation<ServiceDetail, { slug: string; body: Partial<ServiceDetail> }>({
      query: ({ slug, body }) => ({ url: `/services/${slug}`, method: "PATCH", body }),
      invalidatesTags: ["Service", "Content"],
    }),
    getConsultationTypes: builder.query<ConsultationType[], void>({
      query: () => "/consultation-types",
      transformResponse: (response: unknown) => asList<ConsultationType>(response),
    }),
    getConsultants: builder.query<PublicConsultant[], void>({
      query: () => "/consultants",
      transformResponse: (response: unknown) => asList<PublicConsultant>(response),
    }),
    getDashboard: builder.query<ApplicationDashboard, void>({
      query: () => "/applications/dashboard",
      providesTags: ["Application"],
    }),
    getApplications: builder.query<Paginated<ApplicationList>, ApplicationQuery | void>({
      query: (args) => ({ url: "/applications", params: args ?? undefined }),
      transformResponse: (response: unknown) => asPage<ApplicationList>(response),
      providesTags: ["Application"],
    }),
    getApplication: builder.query<ApplicationDetail, number>({
      query: (id) => `/applications/${id}`,
      providesTags: (_result, _error, id) => [{ type: "Application", id }],
    }),
    createApplication: builder.mutation<ApplicationDetail, ApplicationCreateRequest>({
      query: (body) => ({ url: "/applications", method: "POST", body }),
      invalidatesTags: ["Application"],
    }),
    transitionApplication: builder.mutation<ApplicationDetail, { id: number; body: ApplicationTransitionRequest }>({
      query: ({ id, body }) => ({ url: `/applications/${id}/transition`, method: "POST", body }),
      invalidatesTags: (_result, _error, arg) => ["Application", { type: "Application", id: arg.id }],
    }),
    assignApplication: builder.mutation<ApplicationDetail, { id: number; body: ApplicationAssignRequest }>({
      query: ({ id, body }) => ({ url: `/applications/${id}/assign`, method: "POST", body }),
      invalidatesTags: (_result, _error, arg) => ["Application", { type: "Application", id: arg.id }],
    }),
    addApplicationNote: builder.mutation<ApplicationNote, { id: number; body: ApplicationNoteCreateRequest }>({
      query: ({ id, body }) => ({ url: `/applications/${id}/notes`, method: "POST", body }),
      invalidatesTags: (_result, _error, arg) => [{ type: "Application", id: arg.id }],
    }),
    getApplicationStatuses: builder.query<ApplicationStatus[], void>({
      query: () => "/application-statuses",
      transformResponse: (response: unknown) => asList<ApplicationStatus>(response),
    }),
    getApplicationTracking: builder.query<ApplicationTracking, number>({
      query: (id) => `/applications/${id}/tracking`,
      providesTags: (_result, _error, id) => [
        { type: "Tracking", id },
        { type: "Application", id },
      ],
    }),
    updateApplicationTracking: builder.mutation<ApplicationTracking, { id: number; body: TrackingDetailsUpdate }>({
      query: ({ id, body }) => ({ url: `/applications/${id}/tracking`, method: "PATCH", body }),
      invalidatesTags: (_result, _error, arg) => ["Application", "Tracking", { type: "Tracking", id: arg.id }, { type: "Application", id: arg.id }],
    }),
    refreshApplicationTracking: builder.mutation<ApplicationTracking, number>({
      query: (id) => ({ url: `/applications/${id}/tracking/refresh`, method: "POST" }),
      invalidatesTags: (_result, _error, id) => ["Application", "Tracking", { type: "Tracking", id }, { type: "Application", id }],
    }),
    getApplicationTrackingHistory: builder.query<ApplicationTrackingHistoryItem[], number>({
      query: (id) => `/applications/${id}/tracking/history`,
      providesTags: (_result, _error, id) => [{ type: "Tracking", id }],
    }),
    recordManualTracking: builder.mutation<ApplicationTracking, { id: number; body: ManualTrackingUpdate }>({
      query: ({ id, body }) => ({ url: `/applications/${id}/tracking/manual`, method: "POST", body }),
      invalidatesTags: (_result, _error, arg) => ["Application", "Tracking", { type: "Tracking", id: arg.id }, { type: "Application", id: arg.id }],
    }),
    getExternalTrackingAdmin: builder.query<Paginated<ExternalTrackingAdminRow>, { search?: string; page?: number } | void>({
      query: (args) => ({ url: "/admin/applications/external-tracking", params: args ?? undefined }),
      transformResponse: (response: unknown) => asPage<ExternalTrackingAdminRow>(response),
      providesTags: ["Tracking"],
    }),
    getSiteSetting: builder.query<SiteSetting, string>({
      query: (key) => `/content/settings/${key}`,
      providesTags: (_result, _error, key) => [{ type: "Content", id: key }],
    }),
    updateSiteSetting: builder.mutation<SiteSetting, { key: string; value: SiteSetting["value"]; description?: string }>({
      query: ({ key, ...body }) => ({ url: `/content/settings/${key}`, method: "PATCH", body }),
      invalidatesTags: (_result, _error, arg) => ["Content", { type: "Content", id: arg.key }],
    }),
    getDocuments: builder.query<Paginated<DocumentSubmission>, DocumentQuery | void>({
      query: (args) => ({ url: "/documents", params: args ?? undefined }),
      transformResponse: (response: unknown) => asPage<DocumentSubmission>(response),
      providesTags: ["Document"],
    }),
    uploadDocument: builder.mutation<DocumentSubmission, { id: number; file: File }>({
      query: ({ id, file }) => {
        const form = new FormData();
        form.append("file", file);
        return { url: `/documents/${id}/upload`, method: "POST", body: form };
      },
      invalidatesTags: ["Document", "Application"],
    }),
    reviewDocument: builder.mutation<DocumentSubmission, { id: number; body: DocumentReviewRequest }>({
      query: ({ id, body }) => ({ url: `/documents/${id}/review`, method: "POST", body }),
      invalidatesTags: ["Document", "Application"],
    }),
    createDocumentRequest: builder.mutation<DocumentRequestRecord, DocumentRequestCreate>({
      query: (body) => ({ url: "/document-requests", method: "POST", body }),
      invalidatesTags: ["Document", "Application"],
    }),
    getDocumentTypes: builder.query<DocumentType[], void>({
      query: () => "/document-types",
      transformResponse: (response: unknown) => asList<DocumentType>(response),
      providesTags: ["DocumentType"],
    }),
    getAppointments: builder.query<Paginated<Appointment>, { page?: number } | void>({
      query: (args) => ({ url: "/appointments", params: args ?? undefined }),
      transformResponse: (response: unknown) => asPage<Appointment>(response),
      providesTags: ["Appointment"],
    }),
    createAppointment: builder.mutation<Appointment, AppointmentCreateRequest>({
      query: (body) => ({ url: "/appointments", method: "POST", body }),
      invalidatesTags: ["Appointment"],
    }),
    confirmAppointment: builder.mutation<Appointment, { id: number; meeting_link?: string; staff_notes?: string }>({
      query: ({ id, ...body }) => ({ url: `/appointments/${id}/confirm`, method: "POST", body }),
      invalidatesTags: ["Appointment"],
    }),
    getAppointmentSlots: builder.query<
      AppointmentSlot[],
      { consultant_id: number; date: string; consultation_type_id?: number }
    >({
      query: (params) => ({ url: "/appointments/slots", params }),
    }),
    getConversations: builder.query<Paginated<Conversation>, void>({
      query: () => "/conversations",
      transformResponse: (response: unknown) => asPage<Conversation>(response),
      providesTags: ["Conversation"],
    }),
    getMessages: builder.query<Message[], number>({
      query: (id) => `/conversations/${id}/messages`,
      transformResponse: (response: unknown) => asList<Message>(response),
      providesTags: (_result, _error, id) => [{ type: "Message", id }],
    }),
    sendMessage: builder.mutation<Message, { id: number; body: SendMessageRequest }>({
      query: ({ id, body }) => ({ url: `/conversations/${id}/messages`, method: "POST", body }),
      invalidatesTags: (_result, _error, arg) => ["Conversation", { type: "Message", id: arg.id }],
    }),
    getInquiries: builder.query<Paginated<Inquiry>, { page?: number; status?: string } | void>({
      query: (args) => ({ url: "/inquiries", params: args ?? undefined }),
      transformResponse: (response: unknown) => asPage<Inquiry>(response),
      providesTags: ["Inquiry"],
    }),
    createInquiry: builder.mutation<Inquiry, InquiryCreateRequest>({
      query: (body) => ({ url: "/inquiries", method: "POST", body }),
      invalidatesTags: ["Inquiry"],
    }),
    setInquiryStatus: builder.mutation<Inquiry, { id: number; body: InquirySetStatusRequest }>({
      query: ({ id, body }) => ({ url: `/inquiries/${id}/set_status`, method: "POST", body }),
      invalidatesTags: ["Inquiry"],
    }),
    getNotifications: builder.query<Paginated<Notification>, void>({
      query: () => "/notifications",
      transformResponse: (response: unknown) => asPage<Notification>(response),
      providesTags: ["Notification"],
    }),
    markNotificationRead: builder.mutation<Notification, number>({
      query: (id) => ({ url: `/notifications/${id}/mark_read`, method: "POST" }),
      invalidatesTags: ["Notification"],
    }),
    markAllNotificationsRead: builder.mutation<MarkAllReadResponse, void>({
      query: () => ({ url: "/notifications/mark_all_read", method: "POST" }),
      invalidatesTags: ["Notification"],
    }),
    getInvoices: builder.query<Paginated<Invoice>, InvoiceQuery | void>({
      query: (args) => ({ url: "/invoices", params: args ?? undefined }),
      transformResponse: (response: unknown) => asPage<Invoice>(response),
      providesTags: ["Invoice"],
    }),
    createInvoice: builder.mutation<Invoice, InvoiceCreateRequest>({
      query: (body) => ({ url: "/invoices", method: "POST", body }),
      invalidatesTags: ["Invoice", "Report"],
    }),
    recordInvoicePayment: builder.mutation<Invoice, { id: number; body: RecordPaymentRequest }>({
      query: ({ id, body }) => ({ url: `/invoices/${id}/record_payment`, method: "POST", body }),
      invalidatesTags: ["Invoice", "Report"],
    }),
    getClientProfile: builder.query<ClientProfile, void>({
      query: () => "/clients/profile/me",
      providesTags: ["ClientProfile"],
    }),
    updateClientProfile: builder.mutation<ClientProfile, ClientProfileUpdate>({
      query: (body) => ({ url: "/clients/profile/me", method: "PATCH", body }),
      invalidatesTags: ["ClientProfile", "Auth"],
    }),
    getClients: builder.query<Paginated<StaffClient>, { search?: string; page?: number } | void>({
      query: (args) => ({ url: "/clients", params: args ?? undefined }),
      transformResponse: (response: unknown) => asPage<StaffClient>(response),
      providesTags: ["Client"],
    }),
    getClient: builder.query<StaffClient, number>({
      query: (id) => `/clients/${id}`,
      providesTags: (_result, _error, id) => [{ type: "Client", id }],
    }),
    getClientActivity: builder.query<ClientActivity[], number>({
      query: (id) => `/clients/${id}/activity`,
      transformResponse: (response: unknown) => asList<ClientActivity>(response),
    }),
    getStaffDirectory: builder.query<Paginated<StaffUser>, { search?: string; role?: string } | void>({
      query: (args) => ({ url: "/staff/directory", params: args ?? undefined }),
      transformResponse: (response: unknown) => asPage<StaffUser>(response),
      providesTags: ["Staff"],
    }),
    getReportsDashboard: builder.query<DashboardStats, void>({
      query: () => "/reports/dashboard",
      providesTags: ["Report"],
    }),
    getAudit: builder.query<Paginated<AuditLog>, { page?: number; search?: string } | void>({
      query: (args) => ({ url: "/audit", params: args ?? undefined }),
      transformResponse: (response: unknown) => asPage<AuditLog>(response),
      providesTags: ["Audit"],
    }),
  }),
});

export const {
  useRegisterMutation,
  useLoginMutation,
  useGetMeQuery,
  useUpdateMeMutation,
  useChangePasswordMutation,
  useGetHomeContentQuery,
  useGetServicesQuery,
  useGetServiceQuery,
  useGetPageQuery,
  useGetFaqsQuery,
  useGetTestimonialsQuery,
  useGetArticlesQuery,
  useGetArticleQuery,
  useGetPublicSeoQuery,
  useGetLandingsQuery,
  useGetLandingQuery,
  useUpdateLandingMutation,
  useUpdatePageMutation,
  useUpdateArticleMutation,
  useUpdateServiceMutation,
  useGetConsultationTypesQuery,
  useGetConsultantsQuery,
  useGetDashboardQuery,
  useGetApplicationsQuery,
  useGetApplicationQuery,
  useCreateApplicationMutation,
  useTransitionApplicationMutation,
  useAssignApplicationMutation,
  useAddApplicationNoteMutation,
  useGetApplicationStatusesQuery,
  useGetApplicationTrackingQuery,
  useUpdateApplicationTrackingMutation,
  useRefreshApplicationTrackingMutation,
  useGetApplicationTrackingHistoryQuery,
  useRecordManualTrackingMutation,
  useGetExternalTrackingAdminQuery,
  useGetSiteSettingQuery,
  useUpdateSiteSettingMutation,
  useGetDocumentsQuery,
  useUploadDocumentMutation,
  useReviewDocumentMutation,
  useCreateDocumentRequestMutation,
  useGetDocumentTypesQuery,
  useGetAppointmentsQuery,
  useCreateAppointmentMutation,
  useConfirmAppointmentMutation,
  useGetAppointmentSlotsQuery,
  useGetConversationsQuery,
  useGetMessagesQuery,
  useSendMessageMutation,
  useGetInquiriesQuery,
  useCreateInquiryMutation,
  useSetInquiryStatusMutation,
  useGetNotificationsQuery,
  useMarkNotificationReadMutation,
  useMarkAllNotificationsReadMutation,
  useGetInvoicesQuery,
  useCreateInvoiceMutation,
  useRecordInvoicePaymentMutation,
  useGetClientProfileQuery,
  useUpdateClientProfileMutation,
  useGetClientsQuery,
  useGetClientQuery,
  useGetClientActivityQuery,
  useGetStaffDirectoryQuery,
  useGetReportsDashboardQuery,
  useGetAuditQuery,
} = api;
