# Generated by Django 5.2.17 on 2026-08-22 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_visible_to_client', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='active', help_text='active | pending | completed | cancelled', max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('progress_weight', models.PositiveSmallIntegerField(default=0, help_text='0-100 contribution when this status is current.')),
                ('is_terminal', models.BooleanField(default=False)),
                ('client_action_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Application statuses',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='OPEN', max_length=24)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['status', 'due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('client_action_required', models.BooleanField(default=False)),
                ('is_visible_to_client', models.BooleanField(default=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('assigned_consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulted_applications', to=settings.AUTH_USER_MODEL)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
