# Generated by Django 5.2.17 on 2026-08-22 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='services.service'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.applicationstatus'),
        ),
        migrations.AddField(
            model_name='applicationtask',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationtimeline',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationtimeline',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationtimeline',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.applicationstatus'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['client', 'status'], name='application_client__3660af_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['assigned_consultant', 'status'], name='application_assigne_f4bb42_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['reference'], name='application_referen_cf5e1b_idx'),
        ),
    ]
